post_up and post_down commands
bigmoby/addon-wireguard-client pull request #5
Opened 2021-04-04 17:09 UTC by vtanjga

# Proposed Changes

For POSTROUTING to work, MASQUERADE on main network interface have set, which is eth0 (at least on RPi). To use wireguard to access other nodes on same local network, forwarding on wg0 interface is set.

## Related Issues

https://github.com/bigmoby/addon-wireguard-client/issues/4

2021-04-04 18:00 UTC, bigmoby requested changes
Please make attention on '%i' variable never declared

2021-04-04 18:19 UTC, vtanjga commented
Wireguard will expand it to the name of the WG interface. I have that same two lines in my client's `/etc/wireguard/wg0.conf` and it works.

2021-04-05 11:20 UTC, bigmoby commented
@vtanjga thanks for this PR but I released a new version of this plugin so you could specify the post_up and post_down commands. Anyway I'm pretty sure that, unless a your peculiar corner case, you cannot solve with 
```post_up="iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
post_down="iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE"```

Enjoy the new version 👍😉

2021-04-05 11:20 UTC, closed without merging

2021-04-05 13:24 UTC, vtanjga commented
I like your parameterized solution more, better than hardcode it. We'll see if this will solve my problem. Thanks!